name: ubuntu
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Compile
        run: |
          make all
      - name: Test
        run: |
          make test
      - name: Test All
        run: |
          make testall